<a href="https://colab.research.google.com/github/nangchung/truyvandaphuong/blob/main/boolean_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import thư viện

In [1]:
import glob
import re
import numpy as np
import string

lấy file text từ drive

In [2]:

text_file_paths= glob.glob('/content/drive/My Drive/truy van da phuong/databai2/*.txt')
print(text_file_paths)

['/content/drive/My Drive/truy van da phuong/databai2/data2.txt', '/content/drive/My Drive/truy van da phuong/databai2/data1.txt', '/content/drive/My Drive/truy van da phuong/databai2/data5.txt', '/content/drive/My Drive/truy van da phuong/databai2/data3.txt', '/content/drive/My Drive/truy van da phuong/databai2/data4.txt']


In [3]:
lst_content = []
print(lst_content)

[]


đọc các file text và tách từ

In [4]:
dec_=set()
lst_content = []
for file_path in text_file_paths:
  f = open(file_path,'r')
  file = f.read()
	#lst_content.append(file)
	#replace văn bản(loại bỏ kí tự để đưa về caccs word độc lập)và tách từ bằng split()
  word = file.replace('"', '').replace('.', '').replace("'","").lower().split()
	#gộp các word lại để được 1 tập word không trùng lặp từ
  word = set(word)
  lst_content.append(word)
  dec_.update(word)
	#print('tap cac tu ',dec_)
	#print(file)
dec_ = list(dec_)
print(dec_)

['lập', 'lặng', 'đạo', 'toàn,', 'dụ', 'nhất', '2–0', 'xanh', 'điển', 'gov,', 'thế', 'dữ', 'yêu', 'đến', 'bóngnếu', 'tay', 'đăng', 'thăng', 'nghệ', '8', 'sản', 'mạnh,', 'xem)', 'gates', 'phần', 'hay', 'ra', 'cơ', 'tịch', 'cách', 'giải', 'đi', 'về', 'học,', 'vấn', 'mà', 'buổi', 'pirlo', 'nou', 'cỏ', 'nâng', 'hot,', 'tranh', 'chữ', 'blogtamsu', 'hậu', 'tình', '1-1', 'rảnh', 'chuyện', 'lợi', 'lionel', 'luống', 'tan', '33', '199854', 'bố,', 'khí', 'đánh', 'santos', 'tự', 'nam', 'hữu', 'qua', 'rabiot', 'tính', 'ó', 'tải', 'hương', 'vladimir', 'nhiên', 'hội', 'tựa', 'khoa', 'chứ', 'cầu', 'phục', 'hungary', 'nhòa', 'kịch', 'lớn', 'đối', 'tập', 'dậy', 'putin,', 'hoà', 'của', 'bộc', 'mở', 'chung', 'uruguay', 'sai', 'lại,', 'ngôi', 'chiến', 'trách', 'loạn', 'nếu', 'con', 'bàn', 'vậy', 'rio', 'điều', 'hạng', 'olimpico', 'sẵn', 'quá', 'pha', 'alvaro', 'giật', 'phỏng', 'chẽ', 'đào', '7-1', 'gì', 'này', 'năm', 'mộ', 'một', 'phong', 'nguồn', 'sáng', 'bxh', 'argentina', 'mài', 'kết', 'khép', 'chân', 'd

xây dựng ma trận term_docx zero

In [5]:
term_docx = np.zeros((len(dec_),len(text_file_paths)))
print(term_docx)
print('kich thuc ma tran ',term_docx.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
kich thuc ma tran  (725, 5)


đánh chỉ số cho các từ trên mỗi ma trận của văn bản

In [6]:
for k,word in enumerate(dec_):      #k là chỉ số vị trí của từ//vòng lặp tìm từ trong danh sách từ điển
	for i,content in enumerate(lst_content):   #i là chỉ số của văn bản // vòng lặp tìm từ trong văn bản
		if word in content:
			term_docx[k,i]=1
print(term_docx)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]


xử lí câu truy vấn


In [88]:
#query = '"ronaldo" AND "brasil"'
#rất tiếc câu truy vấn theo yêu cầu của thầy không có data nào em thỏa mãn nên đã tự đổi một câu truy vấn khác
query = '"ronaldo" OR "brasil" AND "việt" OR "thích" XOR "xin" OR NOT "yêu" AND NOT "đến"'
query_words = re.findall('"(\w+)"',query)
#query_logic = re.findall(' (\w+)',query)    
key = re.findall('(\w+)',query)

print(query_words)
#print(query_logic)
print(key)


['ronaldo', 'brasil', 'việt', 'thích', 'xin', 'yêu', 'đến']
['OR', 'AND', 'OR', 'XOR', 'OR', 'NOT', 'AND', 'NOT']
['ronaldo', 'OR', 'brasil', 'AND', 'việt', 'OR', 'thích', 'XOR', 'xin', 'OR', 'NOT', 'yêu', 'AND', 'NOT', 'đến']


hàm tìm vecto của từ truy vấn trong các văn bản mà nó xuất hiện

In [8]:

def vecto(query_word):
  if query_word in query_words:
    try:
          k = dec_.index(query_word)
          word_vec = term_docx[k,:]
          return word_vec
          #print('Vector bieu dien cua ', query_word, ' la: ', word_vec)
    except:
        pass

dòng này để chơi giúp hiển thị các vecto của các từ truy vấn

In [85]:
w = []
for word in query_words:
  w.append(vecto(word))

In [86]:
w

[array([1., 1., 0., 0., 0.]),
 array([0., 0., 0., 1., 0.]),
 array([0., 0., 1., 0., 0.]),
 array([1., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 1.]),
 array([1., 0., 0., 0., 1.]),
 array([0., 1., 1., 1., 0.])]

Các hàm sử lý luận lý: có 4 hàm chính 

In [11]:
def AND(x,y):
  v=np.zeros(len(x))
  for i in range(len(x)):
    if x[i] == 1 and y[i] == 1:
      v[i]=1
    else:
      v[i]=0
  return v

In [15]:
def OR(x,y):
  v=np.zeros(len(x))
  for i in range(len(x)):
    if x[i]==0 and y[i]==0:
      v[i]=0
    else:
      v[i]=1
  return v


In [29]:
def NOT(x):
  v=np.zeros(len(x))
  for i in range(len(x)):
    if x[i]==0:
      v[i]=1
    else:
      v[i]=0
  return v

In [14]:
def XOR(x,y):
  v=np.zeros(len(x))
  for i in range(len(x)):
    if x[i]==y[i]:
      v[i]=0
    else:
      v[i]=1
  return v

In [87]:
#gán kết quả bằng vecto của từ truy vấn đầu tiên
kq=[]
if key[0] == "NOT":
  kq = NOT(vecto(key[1]))
else:
  kq = vecto(key[0])
# dùng vòng for truy vấn từ word đầu tiên đến hết câu truy vấn
for i in range(len(key)):
  if key[i] in query_words:  #bỏ qua nếu là từ truy vấn
   pass
  if key[i]=="NOT":          # bỏ qua nếu biểu thức luận lý là NOT vì đã sử lý bên dưới
    pass
# đoạn sử lý các biểu thức logic trong câu truy vấn
  if key[i]=="AND":
    if key[i+1]=="NOT":
      kq = AND(kq,NOT(vecto(key[i+2])))
    else:
      kq = AND(kq,vecto(key[i+1]))
  if key[i]=="OR":
    if key[i+1]=="NOT":
      kq = OR(kq,NOT(vecto(key[i+2])))
    else:
      kq = OR(kq,vecto(key[i+1]))
  if key[i]=="XOR":
    if key[i+1]=="NOT":
      kq = XOR(kq,NOT(vecto(key[i+2])))
    else:
      kq = XOR(kq,vecto(key[i+1]))

print("vecto văn bản thỏa mã với câu truy vấn là " ,kq)



vecto văn bản thỏa mã với câu truy vấn là  [1. 0. 0. 0. 1.]


vòng for tìm ra văn bản phù hơn với câu truy vấn

In [78]:
for i in range(len(kq)):
  if kq[i]==1:
    print(text_file_paths[i])
  else:
    pass
  

/content/drive/My Drive/truy van da phuong/databai2/data2.txt
/content/drive/My Drive/truy van da phuong/databai2/data4.txt


xử lý luận lý của câu truy vấn
