<a href="https://colab.research.google.com/github/nangchung/truyvandaphuong/blob/main/b%C3%A0i_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#Nhập ma trận 
print("Kích thước của ma trận: ")
n = int(input().strip())
matrix = []
for i in range(n):
  print("Nhập dòng thứ", i+1)
  entries = list(map(int, input().split()))
  matrix.append(entries)
matrix = np.array(matrix)
kernel = np.array([[0, 0, 0],
                   [0, 0.5, 0],
                   [0, 1, 0.5]])
#Số lần cần chạy trên hàng và cột của ma trận 
m = n - kernel.shape[0]+1 #

Kích thước của ma trận: 
3 
Nhập dòng thứ 1
7 2 4
Nhập dòng thứ 2
1 9 6
Nhập dòng thứ 3
3 0 5


# Cross Correlation

In [3]:
def Cross_Correlation(matrix, kernel, m):
  kq = np.zeros((n,n), dtype=object)
  #vòng lặp chạy trên hàng j và cột j của ma trận
  for i in range(m):
    for j in range(m):
      sum = 0
      #chạy vòng lặp để thực hiện phép nhân giữa ma trận và kernel
      for u in range(kernel.shape[0]):
        for v in range(kernel.shape[1]):
          a = matrix[u+i, v+j] 
          b = kernel[u,v]
          sum += (a*b)
      #lưu kết quả đã nhân vào ma trận mới
      kq[i+1,j+1] = int(sum) 
  return np.array(kq)
print(Cross_Correlation(matrix, kernel, m))


[[0 0 0]
 [0 7 0]
 [0 0 0]]


# Convolution

In [4]:
def Convolution(matrix, kernel, m):
  kq1 = np.zeros((n,n), dtype=object)
  for i in range(m):
    for j in range(m):
      sum = 0
      for u in range(kernel.shape[0]):
        for v in range(kernel.shape[1]):
          a = matrix[u+i, v+j]
          b = kernel[-u-1,-v-1]
          sum += (a*b)
      kq1[i+1,j+1] = int(sum)
  return np.array(kq1)
print(Convolution(matrix, kernel, m))

[[0 0 0]
 [0 10 0]
 [0 0 0]]
